# Binance API credentials
API_KEY = 'bg_0b01ffa94b4b6f3c2ba5df488587a91e'
API_SECRET = 'facbe7d57bbfb8c6fd82a39d2ce5dc35eef578058ec667aa5ad2fc02dffa644a'
PASSPHRASE = '9025014840'
# Telegram bot credentials
TELEGRAM_TOKEN = '7426543281:AAHu4Qf_KT6sGBaqUJU5ccFKZroHKrVc9R0'
CHAT_ID = '1385370555'

# Trading symbols
SELECTED_SYMBOLS = ["1000000MOGUSDT", "10000WHYUSDT", "1000RATSUSDT", "1000SATSUSDT", "1000XECUSDT", "1INCHUSDT", "1MBABYDOGEUSDT", 
"AAVEUSDT", "ACHUSDT", "ADAUSDT", "AERGOUSDT", "AGLDUSDT", "ALPHAUSDT", "ANKRUSDT", "APEUSDT", "APTUSDT", "ARKMUSDT", "ARPAUSDT", "ARUSDT", "ASTRUSDT", "ATAUSDT", "ATHUSDT", "AVAXUSDT", "AXSUSDT", 
"BANANAUSDT", "BBUSDT", "BCHUSDT", "BELUSDT", "BICOUSDT", "BIGTIMEUSDT", "BLASTUSDT", "BNBUSDT", "BRETTUSDT", "BTCUSDT",
"C98USDT", "CATIUSDT", 	"CELRUSDT", "CHESSUSDT", "CHZUSDT", "CLOUDUSDT", "COMPUSDT", "COSUSDT", "COTIUSDT", "CRVUSDT", "CTSIUSDT", "CVCUSDT", "CYBERUSDT",
"DARUSDT", "DEGENUSDT", "DENTUSDT", "DIAUSDT", "DOGEUSDT", "DOGUSDT", "DOTUSDT", "DYMUSDT", 
"EIGENUSDT", "ENAUSDT", "ENJUSDT", "EOSUSDT", "ETHUSDT", "FETUSDT", "FIDAUSDT", "FILUSDT", "FLUXUSDT", "FTMUSDT", "FTNUSDT", "FXSUSDT", 
"GALAUSDT", "GMCI30USDT", "GMXUSDT", "GOATUSDT", "GRASSUSDT", "GRTUSDT", "GTCUSDT", "GUSDT", "HMSTRUSDT", "HOOKUSDT", "HOTUSDT", "ICPUSDT", "ICXUSDT", "IDUSDT", "IMXUSDT", "IOSTUSDT", "IOTAUSDT", "JOEUSDT", "JUPUSDT", 
"KASUSDT", "KAVAUSDT", "KMNOUSDT", "KNCUSDT", "KSMUSDT", "LEVERUSDT", "LINKUSDT", "LISTAUSDT", "LITUSDT", "LOOKSUSDT", "LPTUSDT", "LQTYUSDT", "LRCUSDT", "LTCUSDT", "LUMIAUSDT", "LUNAUSDT", 
"MAGICUSDT", "MANAUSDT", "MANTAUSDT", "MASKUSDT", "MAVIAUSDT", "METISUSDT", "MEWUSDT", "MKRUSDT", "MOODENGUSDT", "MOVRUSDT", "MYROUSDT", "NEARUSDT", "NEIROCTOUSDT", "NEIROUSDT", "NEOUSDT", "NFPUSDT", "NKNUSDT", "NOTUSDT", "NTRNUSDT", "NULSUSDT", 
"OGUSDT", "OMNI1USDT", 	"ONDOUSDT", "ONEUSDT", 	"OPUSDT", "ORBSUSDT", "ORDERUSDT", "ORDIUSDT", "PAXGUSDT", "PENDLEUSDT", "PEOPLEUSDT", "PHBUSDT", "POLYXUSDT", "PONKEUSDT", "POPCATUSDT", "PORTALUSDT", "POWRUSDT", "PUFFERUSDT", "PYTHUSDT", 
"QNTUSDT", "QTUMUSDT", "QUICKUSDT", "RAYUSDT", "REIUSDT", "REZUSDT", "RPLUSDT", "RUNEUSDT", "RVNUSDT", 
"SAGAUSDT", "SANTOSUSDT", "SEIUSDT", "SFPUSDT", "SHIBUSDT", "SKLUSDT", "SNXUSDT", "SOLUSDT", "SPELLUSDT", "SPXUSDT", "SSVUSDT", "STGUSDT", "STGUSDT", "STMXUSDT", "STXUSDT", "SUIUSDT", "SUSHIUSDT", "SYNUSDT", "SYSUSDT", "TAOUSDT", "TIAUSDT", "TROYUSDT", "TRUUSDT", "TRXUSDT", "TURBOUSDT", "TUSDT", 
"UMAUSDT", "UNIUSDT", "UXLINKUSDT", "VOXELUSDT", "WAXPUSDT", "WIFUSDT", "WLDUSDT", "XRPUSDT", "XUSDT", "ZETAUSDT", "ZILUSDT", "ZKJUSDT", "ZROUSDT"
]
