
# Binance API credentials
API_KEY = 'IDSCsvxMqhtJ8aDxKrAqDdgRTIrGT3qQ8F2ROGp8C0iUIfV0rFffMI2dPcUiR3ZX'
API_SECRET = 'OfCH8GVt0RgzA0lXVq6l4b5NOXC1A7W8rPMM7MvpsYWwD9QjTwTEzD9Z7heFWf41'

# Telegram bot credentials
TELEGRAM_TOKEN = '7124807761:AAFeEIuLTN1VzLyunmVU4m-uEcLhaRQLN_Y'
CHAT_ID = '1385370555'

# Trading symbols
SELECTED_SYMBOLS = [
    'AAVE/USDT', 'ACE/USDT', 'ACH/USDT', 'ADA/USDT', 'AEVO/USDT',
    'AGLD/USDT', 'ALGO/USDT', 'ALICE/USDT', 'ALPHA/USDT',
    'ALT/USDT', 'AMB/USDT', 'APT/USDT', 'ARB/USDT', 'ARK/USDT',
    'ARPA/USDT', 'AR/USDT', 'ASTR/USDT', 'ATA/USDT', 'ATOM/USDT',
    'AUCTION/USDT', 'AVAX/USDT', 'AXL/USDT', 'AXS/USDT', 'BADGER/USDT',
    'BAKE/USDT', 'BAL/USDT', 'BAND/USDT', 'BAT/USDT', 'BB/USDT',
    'BCH/USDT', 'BEAMX/USDT', 'BEL/USDT', 'BICO/USDT',
    'BLUR/USDT', 'BLZ/USDT', 'BNB/USDT', 'BNT/USDT', 'BNX/USDT',
    'BOME/USDT', 'BOND/USDT', 'BSV/USDT', 'BTC/USDT',
    'CAKE/USDT', 'CELO/USDT', 'CELR/USDT', 'CFX/USDT', 'CHR/USDT',
    'CKB/USDT', 'COMBO/USDT', 'COTI/USDT', 'CRV/USDT',
    'CTSI/USDT', 'CYBER/USDT', 'DAR/USDT', 'DASH/USDT',
    'DENT/USDT', 'DOGE/USDT', 'DOT/USDT', 'DUSK/USDT',
    'DYDX/USDT', 'DYM/USDT', 'EDU/USDT', 'EGLD/USDT', 'ENA/USDT',
    'ENJ/USDT', 'ENS/USDT', 'EOS/USDT', 'ETC/USDT', 'ETHFI/USDT',
    'ETH/USDT', 'FET/USDT', 'FIL/USDT', 'FLM/USDT',
    'FLOW/USDT', 'FRONT/USDT', 'FTM/USDT', 'FXS/USDT', 'GAS/USDT',
    'GLM/USDT', 'GMX/USDT', 'GRT/USDT', 'GTC/USDT', 'HBAR/USDT',
    'HFT/USDT', 'HIFI/USDT', 'HIGH/USDT', 'HOOK/USDT', 'ICP/USDT',
    'ID/USDT', 'INJ/USDT',
    'JASMY/USDT', 'JOE/USDT', 'JTO/USDT', 'JUP/USDT', 
    'KEY/USDT', 'KLAY/USDT', 'LDO/USDT', 'LEVER/USDT',
    'LINA/USDT', 'LINK/USDT', 'LIT/USDT',
    'LSK/USDT', 'LTC/USDT', 'MAGIC/USDT', 'MANTA/USDT',
    'MASK/USDT', 'MATIC/USDT', 'MEME/USDT', 'METIS/USDT',
    'MINA/USDT', 'NEAR/USDT', 'NKN/USDT', 'OGN/USDT', 'OMG/USDT', 'OMNI/USDT', 'ONE/USDT', 'ONG/USDT', 'OP/USDT',
    'PENDLE/USDT', 'PEOPLE/USDT', 'PHB/USDT', 'PORTAL/USDT',
    'POWR/USDT', 'PYTH/USDT', 'REN/USDT', 'REZ/USDT',
    'ROSE/USDT', 'RSR/USDT', 'RUNE/USDT', 'RVN/USDT', 'SAGA/USDT',
    'SAND/USDT', 'SEI/USDT', 'SNX/USDT', 'SOL/USDT',
    'SPELL/USDT', 'STEEM/USDT', 'STG/USDT', 'STMX/USDT', 'STORJ/USDT',
    'STRK/USDT', 'STX/USDT', 'SUI/USDT', 'SUPER/USDT', 'SUSHI/USDT',
    'SXP/USDT', 'THETA/USDT', 'TLM/USDT',
    'TNSR/USDT', 'TRB/USDT',
    'TRX/USDT', 'TWT/USDT', 'UMA/USDT', 'UNFI/USDT', 'UNI/USDT', 'VANRY/USDT', 'VET/USDT', 'WAXP/USDT',
    'WIF/USDT', 'WLD/USDT', 'XEM/USDT', 'XLM/USDT',
    'XMR/USDT', 'XRP/USDT', 'XTZ/USDT',
    'XVS/USDT', 'ZEC/USDT', 'ZEN/USDT',
    'ZIL/USDT', 'ZK/USDT', 'ZRO/USDT', 'ZRX/USDT'
]
