
# Binance API credentials
API_KEY = 'IDSCsvxMqhtJ8aDxKrAqDdgRTIrGT3qQ8F2ROGp8C0iUIfV0rFffMI2dPcUiR3ZX'
API_SECRET = 'OfCH8GVt0RgzA0lXVq6l4b5NOXC1A7W8rPMM7MvpsYWwD9QjTwTEzD9Z7heFWf41'

# Telegram bot credentials
TELEGRAM_TOKEN = '7124807761:AAFeEIuLTN1VzLyunmVU4m-uEcLhaRQLN_Y'
CHAT_ID = '1385370555'

# Trading symbols
SELECTED_SYMBOLS = [
    'BTC/USDT', 'ETH/USDT', 'BNB/USDT', 'XRP/USDT', 'ADA/USDT',
    'SOL/USDT', 'DOGE/USDT', 'DOT/USDT', 'UNI/USDT', 'LTC/USDT',
    'LINK/USDT', 'BCH/USDT', 'MATIC/USDT', 'XLM/USDT', 'ATOM/USDT',
    'ETC/USDT', 'FIL/USDT'
]
